version: '3'
services:
  verdaccio:
    image: verdaccio/verdaccio
    user: root
    container_name: "verdaccio"
    network_mode: "bridge"
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "/home/verdaccio/storage:/verdaccio/storage"
      - "/home/verdaccio/conf:/verdaccio/conf"
      - "/home/verdaccio/plugins:/verdaccio/plugins"
    network_mode: "bridge"
